[package]
name = "near-rpc-error-macro"
version = "0.1.0"
authors = ["Alexey <alexey@fckt.dev>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
serde = "1.0"
serde_json = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"]}
quote = "1.0"
proc-macro2 = "1.0"
